RTS:
  headerApiKey: RTS@2017
  imagePath: /Users/raghu/images/
  koronaProductsUrl : https://128.koronacloud.com/web/api/v1/{token}/products/page/{limit}/{offset}/
  koronaLimit: 1000
  koronaProductsUpdateUrl: https://128.koronacloud.com/api/v1/{token}/products/updates/{revision}/{limit}/{offset}
  syncLimit: 500
  koronaUsersUrl : https://128.koronacloud.com/web/api/v1/{token}/users/page/{limit}/{offset}/
  koronaOrganizationalUnitsUrl : https://128.koronacloud.com/web/api/v1/{token}/organizationalUnits/page/{limit}/{offset}/
  coreMenuPath: /Users/raghu/menu/rtsMenu.json
  
